### PR TITLE
order model complete

### PR DESCRIPTION
**Pull request by dionysiaA**
@gooptaa @hkim53 @sbakkila can you please review the order model? we would love to hear your comments! 💃

### CODE REVIEW

**Comment by dionysiaA** [comment]
@hkim53, fair point about not having type as a key but we took as example the users model. Apparently, you can avoid having the type. 👍  please let me know if you still think is necessary to add it in. 🥇

**Comment by sbakkila** [comment]
I prefer keeping the function itself in the present tense, as this is the function that we will call in order to update the status to delivered

**Comment by sbakkila** [comment]
@gooptaa Good point -- we want to write our orderItem model so that we can write an instance method that will  use that association to find the total price. Can you merge this PR so we can move on to that?

**Comment by hkim53** [comment]
Cool

**Pull request merged**
